language: python
python: 2.7
env:
    - TOXENV=flake8
    - TOXENV=lint
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py31
    - TOXENV=py32
    - TOXENV=py33
    - TOXENV=py34
install:
    - pip install tox
script:
    - tox -e $TOXENV
